name: generate-diagram

on:
  push:
    paths:
      - 'terraform/assignment1/plan.json'
      - '.github/workflows/generate-diagram.yaml'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: install terraform-visual
        run: npm install -g @terraform-visual/cli

      - name: run terraform-visual
        run: terraform-visual --plan terraform/assignment1/plan.json

      - name: update repository links
        run: |
          find terraform-visual-report -type f -name "*.html" -exec sed -i 's|href="https://github.com/hieven/terraform-visual"|href="https://github.com/opariffazman/astro"|g' {} +        

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./terraform-visual-report
          commit_message: 'chore: updated infrastructure diagram'
